# Generated by Django 5.0.3 on 2024-04-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_all_frogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='achievment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
