# Generated by Django 5.0.3 on 2024-05-10 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_all_frogs', '0002_zabka_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecomment',
            name='Ocena',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
