# Generated by Django 5.0.3 on 2024-04-16 12:26

import django.db.models.deletion
import get_all_frogs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_all_frogs', '0002_alter_achievements_achievment_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='zabka',
            name='token',
            field=models.CharField(default=get_all_frogs.models.generate_token, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='VisitedZabkas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zabka', models.ManyToManyField(related_name='Zabka_place', to='get_all_frogs.zabka')),
            ],
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
