# Generated by Django 5.0.3 on 2024-04-23 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_all_frogs', '0002_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Ocena',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
