# Generated by Django 5.0.3 on 2024-04-16 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_all_frogs', '0003_zabka_token_visitedzabkas_delete_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitedzabkas',
            name='zabka',
        ),
        migrations.AddField(
            model_name='visitedzabkas',
            name='zabka',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='get_all_frogs.zabka'),
            preserve_default=False,
        ),
    ]
