# Generated by Django 5.0.3 on 2024-05-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_all_frogs', '0006_alter_storecomment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='storecomment',
            name='unique_main_comment',
        ),
    ]
